### ISSUE TITLE
Blinky Tile firmware on Fade Candy

### ISSUE THREAD

**Issue by dunk8888** [Blinkinlabs/BlinkyTile#3]
Hi i was wondering if i could load blinky tile firmware on my fadecandy and use it with pattern paint?

**Comment by dunk8888** [comment]
Also does the blinky tile run ws2812b leds too?

**Comment by cibomahto** [comment]
Unfortunately, it's not compatible with the FadeCandy board- it's using a different processor and circuit. You'd need to re-write the firmware and add a flash chip to the FadeCandy board to make it work.

The supported firmware only supports BlinkyTile-style LEDs (DMX signalling with TTL line levels). There's an unsupported 'polyglot' branch that can output WS2812 control signals, but it is unstable.

The 'controller_pcb_tiny/' branch was a prototype of a smaller controller, but is also unfortunately not supported. If you're new to microcontroller development, I'd recommend using a different platform since this one is pretty hacky. In particular, I'd recommend looking at the ESP8266, and take a look at our EightByEight badge- we have support for that in PatternPaint, and the code could fairly easily be modified to output WS2812b outputs.
